---
title: "Connecting to databases from R (and Shiny!)"
author: |
   | Barbara Borges Ribeiro^1
   |
   | 1. RStudio
output: html_document
---

**Keywords**: databases, shiny, DBI, dplyr, pool

**Webpages**: http://shiny.rstudio.com/articles/overview.html, https://github.com/rstudio/pool

Connecting to an external database from *R* can be challenging. To demystify this, I'll go over three important packages that help you out. The **DBI** package does a great job of standardizing how to establish a connection, execute queries using *SQL* and close the connection. The **dplyr** package builds on top of this to make even easier to connect to databases and extract data, since it allows users to query the database using regular **dplyr** syntax (no *SQL* knowledge necessary). Yet a third package, **pool** exists to make the process of interacting with databases even safer and easier, especially in interactive contexts, like exploration at the console, or within a Shiny application. At the end of the talk, I'll demo a Shiny application that uses these packages. Portions of this talk will assumes minimal familiarity with databases and Shiny.

<!-- TAKE 1

---
title: "Connecting to databases from R (and Shiny!)"
author: |
   | Barbara Borges Ribeiro^1
   |
   | 1. RStudio
output: html_document
---

**Keywords**: databases, shiny, DBI, dplyr, pool

**Webpages**: http://shiny.rstudio.com/articles/overview.html, https://github.com/rstudio/pool

Connecting to an external database from *R* can be challenging. To demystify this, I'll go over three important packages that help you out. The **DBI** package does a great job of standardizing how to establish a connection, execute queries using *SQL* and close the connection. The **dplyr** package builds on top of this to make even easier to connect to databases and extract data, since it allows users to query the database using regular **dplyr** syntax (no *SQL* knowledge necessary). Yet a third package, **pool** exists to make the process of interacting with databases even safer and easier, especially in interactive contexts, like exploration at the console, or within a Shiny application. At the end of the talk, I'll demo a Shiny application that uses these packages. Portions of this talk will assumes minimal familiarity with databases and Shiny.

-->
